In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_excel(r"C:\Users\amanr\Downloads\project\retail-analysis\data\online_retail_II.xlsx")

Understand the Data (EDA)

In [14]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

Purpose 
To understand what the dataset looks like

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

This shows:

data types

missing values

memory usage

df.describe()

This tells:

average price

max quantity

min quantity

distribution of numbers

Companies always do this first.

Data Cleaning

In [19]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

You will see many missing values in:

Customer ID
Description

In [21]:
df = df.dropna()

Explanation:

Missing customers = useless for analysis

Industry practice → remove them

In [22]:
df = df.drop_duplicates()

Explanation:

Sometimes the same invoice is recorded twice.

In [23]:
df = df[df["Quantity"] > 0]

Create Revenue Column

In [25]:
df["Revenue"] = df["Quantity"] * df["Price"]

Example:

Quantity = 10
Price = 5

Revenue = 50

In [26]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

Time Features (Very Important)

Extract Year / Month

In [28]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month

Companies analyze:

seasonal sales

monthly trends

yearly growth

In [30]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12

Total Revenue

In [31]:
total_revenue = df["Revenue"].sum()

print("Total Revenue:", total_revenue)

Total Revenue: 8798233.743999999

This tells the total sales of the company.

Monthly Sales Trend

In [32]:
monthly_sales = df.groupby("Month")["Revenue"].sum()

print(monthly_sales)

Month
1      555802.672
2      504558.956
3      696978.471
4      591982.002
5      597833.380
6      636371.130
7      589736.170
8      602224.600
9      829013.951
10    1033112.010
11    1166460.022
12     994160.380
Name: Revenue, dtype: float64

Explanation:

groupby("Month")

Means:

Jan total sales

Feb total sales

Mar total sales

Best Selling Products

In [34]:
top_products = df.groupby("Description")["Revenue"].sum().sort_values(ascending=False).head(10)

print(top_products)

Description
WHITE HANGING HEART T-LIGHT HOLDER     151339.16
REGENCY CAKESTAND 3 TIER               143727.60
Manual                                  98531.99
ASSORTED COLOUR BIRD ORNAMENT           70291.03
JUMBO BAG RED RETROSPOT                 51644.25
POSTAGE                                 48741.08
ROTATING SILVER ANGELS T-LIGHT HLDR     40156.05
PAPER CHAIN KIT 50'S CHRISTMAS          36871.55
PARTY BUNTING                           35017.30
EDWARDIAN PARASOL NATURAL               34044.75
Name: Revenue, dtype: float64

This shows:

Top 10 products generating revenue

Companies use this for:

inventory planning

marketing

Worst Selling Products

In [35]:
worst_products = df.groupby("Description")["Revenue"].sum().sort_values().head(10)

print(worst_products)

Description
PADS TO MATCH ALL CUSHIONS            0.014
PINK HEART CHRISTMAS DECORATION       0.380
CHAMPAGNE TRAY BLANK CARD             0.380
HAPPY BIRTHDAY GINGER CAT CARD        0.380
SILICON CUBE 25W, BLUE                0.420
CAT W SUNGLASSES BLANK CARD           0.760
OWLS CHARLOTTE BAG                    0.850
BLUE WHITE PLASTIC RINGS LAMPSHADE    0.850
UBO-LIGHT TRIOBASE BLUE               0.850
HAPPY BIRTHDAY CARD TEDDY/CAKE        0.950
Name: Revenue, dtype: float64

Companies remove these products.

Sales by Country

In [37]:
country_sales = df.groupby("Country")["Revenue"].sum().sort_values(ascending=False)

print(country_sales)

Country
United Kingdom          7381644.433
EIRE                     356041.860
Netherlands              268784.350
Germany                  202025.391
France                   146107.070
Sweden                    53147.990
Denmark                   50906.850
Spain                     47568.650
Switzerland               43921.390
Australia                 31446.800
Channel Islands           24546.320
Belgium                   24537.580
Norway                    23944.180
Portugal                  23843.460
Italy                     15052.730
Greece                    14335.670
Austria                   13414.330
Cyprus                    11347.100
Japan                      9722.020
Finland                    7379.460
United Arab Emirates       7300.410
Unspecified                5946.580
Malta                      5373.500
Lithuania                  4892.680
USA                        4786.470
Singapore                  4037.770
Poland                     3567.800
Israel                     3199.400
Thailand                   3070.540
Iceland                    1323.320
Canada                     1216.660
Korea                      1118.510
RSA                         931.430
Bahrain                     805.970
West Indies                 536.410
Brazil                      268.270
Nigeria                     140.390
Name: Revenue, dtype: float64

Insight example:

UK = highest sales
France = second
Germany = third

Companies use this for market expansion.

Top Customers

In [39]:
top_customers = df.groupby("Customer ID")["Revenue"].sum().sort_values(ascending=False).head(10)

print(top_customers)

Customer ID
18102.0    349164.35
14646.0    248396.50
14156.0    196549.74
14911.0    152121.22
13694.0    131443.19
17511.0     84541.17
15061.0     83284.38
16684.0     80489.21
16754.0     65500.07
17949.0     60117.60
Name: Revenue, dtype: float64

This identifies:

VIP customers

Companies target them with discounts.

Average Order Value

In [40]:
avg_order_value = df.groupby("Invoice")["Revenue"].sum().mean()

print("Average Order Value:", avg_order_value)

Average Order Value: 457.8836192557897

Very important business metric.